#!/usr/bin/env python3
"""Build the easy-to-upload DesktopDiary GitHub HTML.

The generated file contains all local JavaScript and CSS, but deliberately keeps
large artwork and fonts in assets/ and companions/. Those folders only need to
be uploaded again when their contents change.
"""

from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "desktop-diary.html"
OUTPUTS = (
    ROOT / "desktop-diary-github-deploy.html",
    ROOT / "desktop-diary-standalone.html",
)
MAIN_BUNDLE = ROOT / "scripts" / "desktop-diary.js"


def strip_query(path: str) -> str:
    return path.split("?", 1)[0].split("#", 1)[0]


def inline_stylesheet(match: re.Match[str]) -> str:
    href = match.group("href")
    local_path = ROOT / strip_query(href)
    if not local_path.is_file():
        return match.group(0)

    css = local_path.read_text(encoding="utf-8")
    if href.startswith("styles/"):
        css = css.replace("url('../assets/", "url('assets/")
        css = css.replace('url("../assets/', 'url("assets/')
        css = css.replace("url(../assets/", "url(assets/")
        css = css.replace("url('../companions/", "url('companions/")
        css = css.replace('url("../companions/', 'url("companions/')
        css = css.replace("url(../companions/", "url(companions/")
    elif href.startswith("companions/"):
        css = re.sub(r"url\((['\"]?)sprites/", r"url(\1companions/sprites/", css)

    return f'<style data-bundled-from="{strip_query(href)}">\n{css}\n</style>'


def inline_script(match: re.Match[str]) -> str:
    src = match.group("src")
    if src.startswith(("http://", "https://", "//")):
        return match.group(0)
    local_path = ROOT / strip_query(src)
    if not local_path.is_file():
        return match.group(0)
    javascript = local_path.read_text(encoding="utf-8")
    return f'<script data-bundled-from="{strip_query(src)}">\n{javascript}\n</script>'


def refresh_canonical_main_bundle(html: str) -> str:
    """Refresh a previously inlined app bundle without disturbing other assets."""
    javascript = MAIN_BUNDLE.read_text(encoding="utf-8")
    replacement = (
        '<script data-bundled-from="scripts/desktop-diary.js">\n'
        f"{javascript}\n"
        "</script>"
    )
    pattern = (
        r'<script data-bundled-from=["\']scripts/desktop-diary\.js["\']>'
        r'.*?</script>'
    )
    refreshed, count = re.subn(pattern, lambda _: replacement, html, count=1, flags=re.DOTALL)
    if count not in (0, 1):
        raise RuntimeError("unexpected number of inlined DesktopDiary bundles")
    return refreshed


def build(html: str) -> str:
    html = re.sub(
        r'<link\b(?=[^>]*\brel=["\']stylesheet["\'])(?=[^>]*\bhref=["\'](?P<href>[^"\']+)["\'])[^>]*>',
        inline_stylesheet,
        html,
        flags=re.IGNORECASE,
    )
    html = re.sub(
        r'<script\b(?=[^>]*\bsrc=["\'](?P<src>[^"\']+)["\'])[^>]*>\s*</script>',
        inline_script,
        html,
        flags=re.IGNORECASE,
    )
    banner = (
        "<!-- Generated by tools/build_github_deploy.py. "
        "Edit the source files, not this compiled copy. -->\n"
    )
    return banner + html


def main() -> None:
    source_html = SOURCE.read_text(encoding="utf-8")
    source_html = refresh_canonical_main_bundle(source_html)
    SOURCE.write_text(source_html, encoding="utf-8")
    built = build(source_html)
    for output in OUTPUTS:
        output.write_text(built, encoding="utf-8")
        print(f"built {output.name}: {output.stat().st_size:,} bytes")


if __name__ == "__main__":
    main()
